Adds locks around app_info_map
In fairly rare circumstances (one so far) we have observed the following:

I, [2016-08-18T01:13:25.287297 #3147]  INFO -- : Shutting down app named [hawkeyejava]
D, [2016-08-18T01:13:25.294380 #3147] DEBUG -- : Running rm -f /etc/cron.d/appscale-hawkeyejava
/root/appscale/AppController/djinn.rb:4192:in `rescue in block in regenerate_routing_config': undefined method `[]' for nil:NilClass (NoMethodError)
        from /root/appscale/AppController/djinn.rb:4186:in `block in regenerate_routing_config'
        from /root/appscale/AppController/djinn.rb:4152:in `each'
        from /root/appscale/AppController/djinn.rb:4152:in `regenerate_routing_config'
        from /root/appscale/AppController/djinn.rb:1854:in `job_start'
        from /root/appscale/AppController/djinnServer.rb:173:in `<main>'

that is during a shutdown of the application, we got a crashed because
app_info_map was been teared down. This patch adds locks around any
reading of the @app_info_map to avoid such a situation.